#ifndef __MyProject1AISBuilder__
#define __MyProject1AISBuilder__

/**
@file
Subclass of AISBuilder, which is generated by wxFormBuilder.
*/

#include <format>
#include "MyProjectBase.h"

#include "wx/Log.h"

#include "ais1.h"
#include "ais5.h"

//// end generated include

/** Implementing AISBuilder */
class MyProject1AISBuilder : public AISBuilder
{
	protected:
		// Handlers for AISBuilder events.
		void BN_BuildAIS123OnButtonClick(wxCommandEvent& event) override;
		void BN_SendAIS123OnButtonClick(wxCommandEvent& event) override;
		void BN_BuildAIS5OnButtonClick(wxCommandEvent& event) override;
		void BN_SendAIS5OnButtonClick(wxCommandEvent& event) override;

		void SC_RateOfTurnOnSpinCtrl(wxSpinEvent& event) override
		{
			int ROTAIS = SC_RateOfTurn->GetValue();
			double ROT = (ROTAIS * ROTAIS) / 4.733;
			ST_RateOfTurn->SetLabel(std::format("{:3.1f}",ROT));
		};

	public:
		/** Constructor */
		MyProject1AISBuilder( wxWindow* parent );
	//// end generated class members



	ais1 m_ais1;
	ais5 m_ais5;



};

#endif // __MyProject1AISBuilder__
