#ifndef __MyProject1CoTSender__
#define __MyProject1CoTSender__

/**
@file
Subclass of CoTSender, which is generated by wxFormBuilder.
*/

#include "MyProjectBase.h"

//// end generated include

/** Implementing CoTSender */
class MyProject1CoTSender : public CoTSender
{
	protected:
		// Handlers for CoTSender events.
		void BN_SendOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MyProject1CoTSender( wxWindow* parent );
	//// end generated class members

};

#endif // __MyProject1CoTSender__
