#ifndef __MyProject1CoTSender__
#define __MyProject1CoTSender__

/**
@file
Subclass of CoTSender, which is generated by wxFormBuilder.
*/

#include "MyProjectBase.h"

//// end generated include

/** Implementing CoTSender */
class MyProject1CoTSender : public CoTSender
{
	protected:
		// Handlers for CoTSender events.
		void BN_SendOnButtonClick( wxCommandEvent& event );
		void BN_AtoNOnButtonClick(wxCommandEvent& event) override;
		void BN_PinkOnButtonClick(wxCommandEvent& event) override;
		void BN_ShipOnButtonClick(wxCommandEvent& event) override;
		void BN_ClearOnButtonClick(wxCommandEvent& event) override;
		void BN_USCGOnButtonClick(wxCommandEvent& event) override;

		void ClearUI();
		void SendTakMessage();


	public:
		/** Constructor */
		MyProject1CoTSender( wxWindow* parent );
	//// end generated class members

};

#endif // __MyProject1CoTSender__
